# name: CD

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Check out the code
#       uses: actions/checkout@v2

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2

#     - name: Log in to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     - name: Build Docker image
#       run: |
#         docker build -t surendar2011/simple-app:latest .
#         docker tag surendar2011/simple-app:latest surendar2011/simple-app:${GITHUB_SHA}

#     - name: Push Docker image
#       run: |
#         docker push surendar2011/simple-app:latest
#         docker push surendar2011/simple-app:${GITHUB_SHA}

name: CD

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get Latest Version Tag
      id: get_version
      run: |
        # Get the latest tag or default to v1.1.1 if no tag exists
        VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "Latest tag is $VERSION"
        
        if [[ -z "$VERSION" ]]; then
          VERSION="v1.1.1"  # If no tag exists, start with v1.1.1
        else
          # Increment the patch version (simplified version increment)
          VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++;print}')
        fi
        echo "New version will be $VERSION"
        
        # Set the version for use in subsequent steps
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        # Use the version from the previous step
        docker build -t surendar2011/simple-app:${{ env.VERSION }} .
        docker tag surendar2011/simple-app:${{ env.VERSION }} surendar2011/simple-app:latest

    - name: Push Docker image
      run: |
        docker push surendar2011/simple-app:${{ env.VERSION }}
        docker push surendar2011/simple-app:latest

