name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t simple-app .

    - name: Lint Dockerfile
      run: |
        docker run --rm hadolint/hadolint < Dockerfile

    - name: Run Tests (if applicable)
      run: |
        # Add your test commands here, e.g., unit tests for your app
        echo "No tests to run for this example."

